geoalchemy/geoalchemy2

- doc/index.rst
This adds @loicgasser to the list of contributors.
> Add Loïc Gasser to the contributors list

- geoalchemy2/elements.py
- tests/test_elements.py
This is an alternative to https://github.com/geoalchemy/geoalchemy2/pull/129, as discussed with @b11z. Thank you @b11z for the initial patch.
> Fix SpatialElement.__str__ on Python 3

- geoalchemy2/__init__.py
- geoalchemy2/types.py
- tests/test_functional.py
[AddGeometryColumn](http://postgis.net/docs/AddGeometryColumn.html) has a parameter `use_typmod` which when set to `false` will create explicit constraints for dimension, SRID and geometry type instead of relying on the build-in types (for PostGIS 2.x).
This PR proposes to add a parameter `use_typmod` to `_GISType` which will be passed on to `AddGeometryColumn`.
> Add use_typmod option for AddGeometryColumn

- .travis.yml
- geoalchemy2/__init__.py
- geoalchemy2/types.py
- requirements.txt
A new version of flake8 and pycodestyle was released on Monday, which broke the Travis build. This PR fixes the linter issues.
Also I am proposing to pin down the versions of the development dependencies to have a reproducible build.
> Adapt code style to new version of flake8/pycodestyle

- geoalchemy2/exc.py
- geoalchemy2/types.py
- tests/test_types.py
This PR add checks for the arguments passed to the `_GISType` constructor.
@tsauerwein, what do you think about that? I think it's a good idea to catch errors as early as possible, and warn the user when appropriate.
> Add checks to _GISType constructor

- geoalchemy2/comparator.py
It is just a minor fix in a docstring: instead of comparing to see if it is to the right, we are comparing to see if it is above.
> Fix docstring for overlaps_or_above

- geoalchemy2/functions.py
- tests/test_functions.py
The function returns a number, not a `types.Geometry`.
See https://postgis.net/docs/ST_LineLocatePoint.html
> Fix ST_LineLocatePoint return type

- geoalchemy2/types.py
- tests/test_types.py
Raise an `exc.ArgumentError` in case of incompatible `geometry_type` and `dimension` parameters. Avoid the issues mentioned in #67 and #157.
> Dimension validation

- RELEASE.rst
- doc/spatialite_tutorial.rst
- geoalchemy2/elements.py
- geoalchemy2/types.py
This PR follows up on #209.
Ping @SergeBouchut and @adrien-berchet-forcity. Also, please tell me if you need a new geoalchemy2 release on pypi.
> Improve docs related to EWKB and SRID

- geoalchemy2/types.py
- tests/test_functional.py
- tests/test_functional_spatialite.py
GeoAlchemy does not currently support WKBElement objects as bind values. We even have a [a comment in the tests](https://github.com/geoalchemy/geoalchemy2/blob/3b4041620907b5cc0a387eb15749d53251e89e77/tests/test_functional.py#L158-L160) for that issue.
Also, Issue #220 has recently revealed problems with lazy spatial relationships because of that lack.
This PR fixes the problem by extending the `bind_processor` function, making it support WKBElement bind-values. The function relies on Shapely for converting the WKBElement into a WKT string. It just throws an exception when Shapely is not available.
> Support WKBElement as bind values

- doc/orm_tutorial.rst
> Document the use of spatial functions in primaryjoin conditions

- geoalchemy2/functions.py
Do not register `functions.GenericFunction` in `sqlalchemy.sql.functions._registry` for `sqlalchemy>=1.3.4`.
This is not mandatory but it will be more consistent with sqlalchemy.
> Do not register functions.GenericFunction for sqlalchemy>=1.3.4

- geoalchemy2/types.py
- tests/test_types.py
This PR redefines the geometry_type/dimension consistency checks in the `check_ctor_args` function.
A few things to note:
* `dimension` is actually not used when not using `AddGeometryColumn`, so there's no point checking that `dimension` is consistent with `geometry_type` when `management` is `False`
* when `AddGeometryColumn` is used there are constraints in the setting of `geometry_type` and `dimension`.  `AddGeometryColumn` does not support `ZM` geometry types. And when the geometry type ends with `M` or `Z` the dimension must be set to `3`.
Fixes #227.
> Redefine the geometry_type/dimension consistency checks

- geoalchemy2/__init__.py
- tests/test_functional.py
This PR aims to fix #230, where GeoAlchemy assumes that the schema is "public" when no schema is specified by the user.
Closes #230.
> Do not assume the "public" schema

- geoalchemy2/functions.py
- tests/test_functions.py
Add all Geometry constructors.
Reorder the tests so that they are in the same order as the function definitions.
Fixes #156
> Add all geometry constructors

- geoalchemy2/functions.py
- tests/test_functions.py
Hey, I'm adding this because of a warning:
`WARNING:  ST_Distance_Sphere signature was deprecated in 2.2.0. Please use ST_DistanceSphere`
https://postgis.net/docs/ST_DistanceSphere.html
> Add ST_DistanceSphere function, since ST_Distance_Sphere is deprecated

- geoalchemy2/elements.py
- tests/test_elements.py
- tests/test_functional.py
> Raise an AttributeError when accessing a non-st attribute on _SpatialElement

- geoalchemy2/elements.py
- geoalchemy2/functions.py
I tried to understand the origin of #213 and when I add default compilers (as the exception hints) it works properly but breaks many tests for `sqlalchemy < 1.1`, so it may be not the proper way to fix this.
> Add default compilation rules to elements and functions

- geoalchemy2/functions.py
- tests/test_functional.py
- tests/test_functions.py
Fix ST_AsGeoJSON to do nothing when a sqlalchemy.sql.functions.GenericFunction object is found in arguments.
Fixes #267
> Fix ST_AsGeoJSON

- geoalchemy2/elements.py
- geoalchemy2/functions.py
- tests/test_functional.py
The goal of this PR is to be able to add functions whose names do not start with the `ST_*` prefix (like in #291).
> Add an internal function registry

- CHANGES.txt
- RELEASE.rst
The main feature of this release is the internal registry so functions do not need to start with the `ST_` prefix any more.
> Prepare release 0.8.5

- geoalchemy2/__init__.py
- setup.py
We are currently in the process of updating our application in preparation for SQLAlchemy v2.0. The current release of SQLAlchemy is v1.4, which has an environment variable setting (`SQLALCHEMY_WARN_20=1`) which will enable warnings for functionality that will be removed in SQLAlchemy v2.0.
I found that a couple of lines of code in geoalchemy2 emitted a warning in this situation.
```
/Users/robin/anaconda3/envs/pepys_sa14/lib/python3.8/site-packages/geoalchemy2/__init__.py:96: RemovedIn20Warning: The legacy calling style of select() is deprecated and will be removed in SQLAlchemy 2.0.  Please use the new calling style described at select(). (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
stmt = select([func.AddGeometryColumn(*args)])
```
``` …
```
> Fix warnings in preparation for SQLAlchemy v2.0

- geoalchemy2/types.py
- requirements.txt
- tests/gallery/test_summarystatsagg.py
- tests/test_functional.py
In order to support the 'generative' style of select() of sqlalchemy>=2, the
select() function in sqlalchemy==1.4 checks whether the first argument is an
iterable or not. This check is performed using 'hasattr', which actually calls
'getattr' and catch the AttributeError exceptions. Changing the exception
raised in the comparator_factory thus allows the 'select()' function to detect
that the CompositeType should be processed as a clause, not as a list of
clauses.
Fixes #333
> Change KeyError into AttributeError in the comparator_factory of CompositeType

- setup.py
Warehouse now uses the project_urls provided to display links in the sidebar on [this screen](https://pypi.org/project/requests/), as well as including them in API responses to help the automation tool find the source code for Requests.
Docs: [packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#project-urls](https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#project-urls)
> Add GitHub URL for PyPi

- doc/alembic.rst
- geoalchemy2/alembic_helpers.py
- geoalchemy2/types.py
> Add Alembic helpers for Add/Drop columns with SQLite

- geoalchemy2/_functions.py
- tests/test_functions.py
Version 0.9.0 broke my code. My query was returning a string from Box2D(), since version 0.9.0 the call to Box2D() gets wrapped by ST_AsEWKB. This change fixes my problem so I can get a string back from Box2D().
> Functions returning Box types now return None types instead of Geometry types

- geoalchemy2/__init__.py
- geoalchemy2/shape.py
- setup.cfg
`geoalchemy2` is currently fairly slow to import (with and without `__pycache__` being built) and, more importantly, it seems gets substantially slower as the Python environment gets larger. **This is not an issue with `geoalchemy2` itself though**. `SQLAlchemy` is the main culprit for the slow baseline import time and `pkg_resources` is the culprit for the environment size-dependent import time (see: https://github.com/pypa/setuptools/issues/926). 
The PR does two things:
1. Replaces the use of `pkg_resources` in `shape.py` with `packaging` (an existing dependency)
2. Attempts to use `importlib.metadata` instead of `pkg_resources` in `__init__.py`, falling back to `pkg_resources` if you're using Python <3.8
Profiling import time before and after these changes:
```
Tiny (43M):
Before: …
```
> Replace pkg_resources usage with packaging + importlib.metadata

- setup.py
If geoalchemy2.dialects is missing from the packages line of setup.py then then building will either show a big warning, or miss the geoalchemy2.dialects package entirely.
> setup.py needs to know about geoalchemy2.dialects

- geoalchemy2/types/__init__.py
- tests/test_types.py
Currently the column conversion from NullType to Geometry by `SQLAlchemy` is failing due to `NULL` `SRS_ID` from the DB. In such scenario, where a null value is received, function should be able to override it by default value of `-1` rather than trying to convert `NoneType` to `int`. This fix takes into consideration failure and override `NoneType` by default value.
Below is the error that occurred due to missing `SRS_ID`.
```bash
File "/Users/satyamsoni/Documents/alchemy/.venv/lib/python3.11/site-packages/geoalchemy2/types/__init__.py", line 127, in __init__
geometry_type, srid = self.check_ctor_args(
^^^^^^^^^^^^^^^^^^^^^
File "/Users/satyamsoni/Documents/alchemy/.venv/lib/python3.11/site-packages/geoalchemy2/types/__init__.py", line 182, in check_ctor_args
srid = int(srid)
^^^^^^^^^ …
```
> Type: Fix Modified check_ctor_args to pass default SRS_ID value in case of null

- geoalchemy2/types/__init__.py
Allow geometry_type to be None at the type level to match documentation.
Fixes a common type checking error when using geoalchemy
This pull request is:
- Good to go, no issue or tests are needed
(which must include a complete example of the issue).
(which must include a complete example of the feature).
> Allow geometry_type to be None at the type level to match documentation

- geoalchemy2/elements.py
- geoalchemy2/types/dialects/sqlite.py
- tests/__init__.py
- tests/test_functional.py
- tests/test_functional_sqlite.py
Fixes #516 
This pull request is:
- Good to go, no issue or tests are needed
(which must include a complete example of the issue).
(which must include a complete example of the feature).
> Fix: Can handle negative coordinates with Spatialite

- tests/test_functional.py
- tox.ini
Add a test for Geometry type that uses WKT for insertion.
> Test: Add test in test_functional.py for custom Geometry that uses WKT elements

- .github/workflows/test_and_publish.yml
- tox.ini
For unknown reasons the SQLite driver sometimes causes Segmentation Faults in CI with Pypy so we disable it for the Pypy job.
> CI: Fix Pypy job

- geoalchemy2/alembic_helpers.py
The Alembic helpers registering a `create_geospatial_table` operation did not pass additional  keyword arguments to the operation. Additional user-provided arguments like `postgres_partition_by` would therefore get lost when using the `geoalchemy2.alembic_helpers.writer` helper function. Fixes: #532
This pull request is:
- Good to go, no issue or tests are needed
(which must include a complete example of the issue).
(which must include a complete example of the feature).
> Fix: Pass through keyword args for create_geospatial_table(). Fixes: #532
