TEST.rst

Fix typo database name

---

geoalchemy2/compat.py
geoalchemy2/elements.py
tests/test_elements.py

Fix issue #96 
Based on previous pr #86 
Add specific test

Python3 support

---

.travis.yml
RELEASE.rst

Note that this is untested. I need to merge it to be able to test it.
Fixes https://github.com/geoalchemy/geoalchemy2/issues/101.

Use TravisCI to publish PyPI packages

---

doc/conf.py

New mock for Read The Docs

---

.travis.yml
setup.cfg

This PR makes the Travis build create a wheel and upload it to pypi when a tag/release is created.

Distribute GeoAlchemy as wheels

---

README.rst

Yet another badge to README.rst.

Add RTD badge to README.rst

---

doc/core_tutorial.rst
geoalchemy2/elements.py
geoalchemy2/types.py
tests/test_comparator.py
tests/test_elements.py
tests/test_functions.py
tests/test_shape.py
tests/test_types.py

This PR is an alternative to https://github.com/geoalchemy/geoalchemy2/pull/121.

Read geometries with ST_AsEWKB

---

.travis.yml
tests/test_functional.py
tests/test_functions.py

Just noticed that, I think you may want to run the tests through flake8 as well

Fix flake8 in tests

---

geoalchemy2/comparator.py
tests/test_comparator.py

Set result_type when using operators

---

geoalchemy2/functions.py
tests/test_functions.py

Adds support for the ST_AsTWKB function as described here: http://postgis.net/docs/ST_AsEWKB.html

Add ST_AsTWKB function

---

geoalchemy2/types.py
tests/test_types.py

Fixes https://github.com/geoalchemy/geoalchemy2/issues/158.

Support geometry column with no typmod

---

geoalchemy2/elements.py

Adding example of creating a WKTElement with an Extended WKT

Extended WKT WKTElement example

---

.travis.yml
tox.ini

The build fails on Travis. I am creating this PR for testing purpose.

Remove Python 3.3 from the test matrix

---

geoalchemy2/elements.py
tests/test_elements.py
tests/test_functional.py

Supersedes https://github.com/geoalchemy/geoalchemy2/pull/177.

Make WKTElement and WKBElement pickable

---

.flake8
.travis.yml
TEST.rst
doc/index.rst
doc/spatialite_tutorial.rst
geoalchemy2/__init__.py
geoalchemy2/comparator.py
geoalchemy2/compat.py
geoalchemy2/elements.py
geoalchemy2/functions.py
geoalchemy2/types.py
install-spatialite.sh
requirements.txt
tests/test_elements.py
tests/test_functional_spatialite.py
tests/test_types.py
tox.ini

This PR adds SpatialLite support. This is WIP at this point. The code basically works, but I need to do more testing, add more automated tests, and better docs.

Add SpatiaLite support

---

geoalchemy2/shape.py
tests/test_functional_spatialite.py
tests/test_shape.py

Fix to_shape with SpatiaLite

---

geoalchemy2/elements.py
tests/test_elements.py
tests/test_functional.py

Fix the geom unpickling process

---

geoalchemy2/elements.py
tests/test_elements.py

Now geometry result processor preserves query SRID.
```python
geom = conn.scalar(select([func.ST_Transform(func.ST_GeomFromEWKT('SRID=4326;POINT(1 1)'), 2154, type=Geometry(srid=2154))])) 
assert geom.srid == 2154  # previously -1
```
This is made possible by unpacking SRID from WKB struct, when instanciate `WKBElement` without `srid` argument.
```python
geom = WKBElement(b'\x01\x01\x00\x00\x00\xcf\x02\x14\rO\xc8\x18A\x08`\xe4Jw\r0A', extended=True)
assert geom.srid == 2154  # previously -1
```
Note:
- I have swapped  `TestWKBElement` with `TestExtendedWKBElement` test class names.
- Also I set a real WKB binary for `TestExtendedWKBElement` test class: the dummy previous one could not be unpacked.
- It seems that some test cases in `test_functional_spatialite` module, initialize …

Unpack SRID from WKB struct when it is not provided as WKBElement arg

---

geoalchemy2/elements.py
geoalchemy2/types.py
tests/test_elements.py
tests/test_functional.py

Make WKTElement behaviour consistent with the WKBElement one introduced in #209.

Change WKTElement to read SRID from the EWKT string.

---

geoalchemy2/functions.py
tests/test_functions.py

Add some functions.
(this PR is a revival of #187 , #188 and #189)

Add some missing functions

---

geoalchemy2/comparator.py
tests/test_functional.py
tests/test_functional_spatialite.py

Proposal for #215 (I chose to allow lowercase function in this proposal, which might not be what you want)
I am not sure it is the best way to do it but it seems to work as far as I can see.

Lowercase PostGIS functions

---

TEST.rst
tests/test_functional.py

This PR fixes the functional tests on PostGIS 3.

Fix tests with PostGIS 3

---

doc/core_tutorial.rst

As requested in the old issue #110, add reflection example in doc.

Add reflection example in doc

---

geoalchemy2/__init__.py
geoalchemy2/elements.py
geoalchemy2/functions.py
geoalchemy2/types.py
tests/__init__.py
tests/test_elements.py
tests/test_functional.py
tests/test_functions.py
tests/test_types.py

Following #248, I made some tests to try to make it work.
It seems ok except for PyPy.

Continuation of Pr248

---

geoalchemy2/elements.py
geoalchemy2/shape.py
tests/test_elements.py
tests/test_functional.py
tests/test_shape.py

Add __eq__ to wkbelement and make from_shape() able to create extended WKBElement

---

geoalchemy2/functions.py
tests/test_functional.py
tests/test_functional_spatialite.py

Add support of the feature version of St_AsGeoJson()

---

geoalchemy2/elements.py
tests/test_elements.py
tests/test_functional.py

Fix __eq__() method in _SpatialElement

---

geoalchemy2/types.py
tests/test_functional.py

Fix insert/update for RasterElement

---

tests/gallery/test_decipher_raster.py

Add an example of Raster data deciphering

---

.travis.yml
tox.ini

Use tox generative environments

---

tests/gallery/test_summarystatsagg.py

Add an example of composite type with the use of ST_SummaryStatsAgg

---

geoalchemy2/__init__.py
geoalchemy2/types.py
tests/test_functional.py

Add support for N-D index creation. See here from the [Postgis docs](https://postgis.net/workshops/postgis-intro/3d.html#n-d-indexes)
Adds an additional flag "use_N_D_index" to the Geometry options. Checks if the spatial_index is false and will return an ArgumentError.

Add support for N-D index creation

---

geoalchemy2/__init__.py

Fix quotes in index creation

---

geoalchemy2/comparator.py
tests/test_comparator.py

Add support for N-D spatial intersection for querying geometries in bounding boxes
See here for info:
http://postgis.net/docs/geometry_overlaps_nd.html
List of all operators in Postgis
http://postgis.net/docs/reference.html#Operators

Add support for N-D intersects '&&&' operator

---

geoalchemy2/__init__.py
geoalchemy2/types.py
tests/test_functional_spatialite.py
tests/test_types.py

Introduce not nullable column for SQLite

---

geoalchemy2/_functions.py
geoalchemy2/types.py
tests/gallery/test_summarystatsagg.py
tests/test_functional.py

Add SummaryStats type for the ST_SummaryStatsAgg function

---

geoalchemy2/__init__.py
tests/test_functional.py
tests/test_functional_spatialite.py

Fix creation of columns using a TypeDecorator

---

tests/gallery/test_type_decorator.py

Following #371 to improve the example. WDYT @tiptop96?

Improve the gallery example for TypeDecorator

---

geoalchemy2/types.py
tests/test_functional.py

Remove some irrelevant warnings for Raster type

---

geoalchemy2/__init__.py
tests/test_functional.py

Fix: Use empty event for unsupported dialects

---

geoalchemy2/shape.py
geoalchemy2/types/dialects/mysql.py
geoalchemy2/types/dialects/postgresql.py
geoalchemy2/types/dialects/sqlite.py
setup.py

Fix: Shapely remains optional requirement

---

geoalchemy2/admin/dialects/geopackage.py
geoalchemy2/admin/dialects/sqlite.py
tests/__init__.py
tests/conftest.py
tests/test_functional_sqlite.py

Split load_spatialite into load_spatialite_driver and init_spatialite

---

geoalchemy2/utils.py

Fix: Handle empty doctrings in optimized mode

---

.github/workflows/test_and_publish.yml
pyproject.toml
setup.py
test_container/helpers/install_requirements.sh
tox.ini

Build: Add Py312 support

---

geoalchemy2/admin/dialects/mysql.py

Fix: Fix specific compilation rules for MariaDB

---

geoalchemy2/admin/dialects/sqlite.py
geoalchemy2/types/__init__.py
tests/test_functional.py

Fixes #541 
Requires #543 
Should supersede #542

Feat: Improve Geometry initializer to make the dimension optional

---

geoalchemy2/types/__init__.py

Fix: Remove warning message from MySQL/MariaDB reflection
